### Create New User
POST http://localhost:3000/auth/signup
content-Type: application/json

{
    "email":"ron_0391@gmail.com",
    "password":"1234567"
}

### SignIn the User
POST http://localhost:3000/auth/signIn
content-Type: application/json

{
    "email":"john_0392@gmail.com",
    "password":"123456"
}

### Find a user with ID
GET http://localhost:3000/auth/2
content-type: application/json

### Find all users with email
GET http://localhost:3000/auth?email=abc@abc.com
content-type: application/json

### Delete user by id
DELETE  http://localhost:3000/auth/5
content-type: application/json

### Update user by id
PATCH  http://localhost:3000/auth/2
content-type: application/json

{
    "password":"aaa"
}

### GET Signed In User
GET http://localhost:3000/auth/getSignedInUser

### Sign out user
POST http://localhost:3000/auth/signOut